name: keihin00657

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Setup SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: checkout
        uses: actions/checkout@v2
      - name: Commit
        run: |
          git clone --depth=1 git@github.com:labeneko/keihin00657.git keihin00657
          cd keihin00657
          TZ=Asia/Tokyo date '+%Y%m%d%H%M' > time.txt
          git config --local user.email "info@laboneko.jp"
          git config --local user.name "labeneko"
          git add .
          git commit -m "時間を保存" -a || true
          git push origin main
