name: save

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: labeneko/kawamachi
      - name: Commit files
        run: |
          git pull
          TZ=Asia/Tokyo date '+%Y%m%d%H%M' > time.txt
          git config --local user.email "info@laboneko.jp"
          git config --local user.name "labeneko"
          git add .
          git commit -m "時間を保存"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
